shared_params:  # Shared parameters are parameters that must be the same in the generator and evaluator flowgraph
  # Number of packets to send from the generator
  num_packets_to_send: 1000

evaluator_params:
  # This value is used to determine how many bytes to strip from the received packets.
  # If the received packets have already had their sync word removed, keep this at 0.
  sync_word_num_bytes: 4

  # Whether or not Viterbi decoding should be applied
  viterbi_applied: False

  # Whether or not CCSDS descrambling should be applied
  scrambling_applied: True

  # Whether or not Reed Solomon decoding should be applied
  rs_applied: True

  # Directory from which to read the received packets.
  folder_source: "/home/rei/sampleAR2300IQ/encoded_packets"

generator_params:
  # Whether or not to apply Reed Solomon encoding
  rs_applied: True

  # Whether or not to apply CCSDS scrambling
  scrambling_applied: True

  # Synchronization word to use
  sync_word: 0x24804321

  # Number of bytes in the synchronization word
  sync_word_num_bytes: 4

  # Whether or not to apply CCSDS convolutional coding
  viterbi_applied: False

  # Modulation type: Currently only takes FSK
  modulation_type: "FSK"

  # Bit rate
  bit_rate: 300000

  # RF frequency
  rf_freq: 400.0e+6

  # RF radio sampling rate
  rf_samp_rate: 4.0e+6

  # RF radio gain
  rf_gain: 30

  # Channel noise voltage
  channel_noise_voltage: 0.0

# Location to store the analysis report in
report_output_file: "output.yaml"
